---
- name: Setup macOS
  hosts: localhost
  become: false
  connection: local

  vars:
    brew_formulas:
      - awscli
      - bash-completion
      - ca-certificates
      - cloc
      - colima
      - docker
      - docker-compose
      - editorconfig
      - git
      - go
      - grip
      - istioctl
      - java
      - jq
      - kubernetes-cli
      - minikube
      - ngrep
      - nvm
      - shellcheck
      - semgrep
      - siege
      - terraformer
      - tfenv
      - tfsec
      - tig
      - tmux
      - tree
      - vim
      - wget

    brew_casks:
      - android-file-transfer
      - brave-browser
      - dropbox
      - firefox
      - flycut
      - google-chrome
      - google-cloud-sdk
      - google-drive
      - iterm2
      - microsoft-teams
      - pritunl
      - rectangle
      - signal
      - slack
      - spotify
      - visual-studio-code
      - whatsapp
      - zoom

  tasks:
    - name: Install Homebrew formulas
      homebrew:
        name: "{{ brew_formulas }}"
        state: present
      register: result
      until: result is successful

    - name: Install Homebrew casks
      homebrew_cask:
        name: "{{ brew_casks }}"
        state: present
      register: result
      until: result is successful

    - name: Auto hide dock
      osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: true
        state: present

    - name: Set touch bar as expanded control strip
      osx_defaults:
        domain: com.apple.touchbar.agent
        key:    PresentationModeGlobal
        type:   string
        value:  fullControlStrip

    - name: Show hidden files
      osx_defaults:
        domain: com.apple.finder
        key:    AppleShowAllFiles
        type:   bool
        value:  true
