---
- name: Setup macOS
  hosts: localhost
  become: false
  connection: local

  vars:
    brew_formulas:
      - awscli
      - bash-completion
      - black
      - ca-certificates
      - cloc
      - cmake
      - colima
      - docker
      - docker-buildx
      - docker-compose
      - eksctl
      - git
      - go
      - graphviz
      - grip
      - helm
      - isort
      - istioctl
      - java
      - jq
      - kubernetes-cli
      - minikube
      - neovim
      - ngrep
      - nvm
      - prettier
      - pyenv
      - pyenv-virtualenv
      - python-yq
      - reattach-to-user-namespace
      - semgrep
      - shellcheck
      - shfmt
      - siege
      - telnet
      - terraformer
      - tfenv
      - tfsec
      - tig
      - tmux
      - tree
      - vim
      - watch
      - wget

    brew_casks:
      - android-file-transfer
      - brave-browser
      - dropbox
      - firefox
      - flycut
      - google-chrome
      - google-cloud-sdk
      - google-drive
      - iterm2
      - microsoft-teams
      - notion
      - pritunl
      - rectangle
      - signal
      - slack
      - spotify
      - visual-studio-code
      - whatsapp
      - zoom

  tasks:
    - name: Install Homebrew formulas
      homebrew:
        name: "{{ brew_formulas }}"
        state: present
      register: result
      until: result is successful

    - name: Tap Homebrew Nerd Fonts
      homebrew_tap:
        name: homebrew/cask-fonts
        state: present

    - name: Search Nerd Fonts
      command: brew search '/font-.*-nerd-font/'
      register: nerd_fonts

    - name: Install Homebrew casks
      homebrew_cask:
        name: "{{ brew_casks + nerd_fonts.stdout_lines }}"
        state: present
      register: result
      until: result is successful

    - name: Auto hide dock
      osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: true
        state: present

    - name: Set touch bar as expanded control strip
      osx_defaults:
        domain: com.apple.touchbar.agent
        key: PresentationModeGlobal
        type: string
        value: fullControlStrip

    - name: Show hidden files
      osx_defaults:
        domain: com.apple.finder
        key: AppleShowAllFiles
        type: bool
        value: true
