---
- name: Setup macOS
  hosts: localhost
  become: false
  connection: local

  vars:
    brew_formulas:
      - awscli
      - bash-completion
      - ca-certificates
      - cloc
      - colima
      - docker
      - docker-compose
      - editorconfig
      - git
      - go
      - jq
      - kubernetes-cli
      - minikube
      - ngrep
      - nvm
      - shellcheck
      - siege
      - terraform
      - tfsec
      - tig
      - tmux
      - vim
      - wget

    brew_casks:
      - brave-browser
      - dropbox
      - firefox
      - flycut
      - google-drive
      - iterm2
      - pritunl
      - rectangle
      - spotify
      - visual-studio-code
      - whatsapp
      - zoom

  tasks:
    - name: Install Homebrew formulas
      homebrew:
        name: "{{ brew_formulas }}"
        state: present
      register: result
      until: result is successful

    - name: Install Homebrew casks
      homebrew_cask:
        name: "{{ brew_casks }}"
        state: present
      register: result
      until: result is successful
